### ISSUE TITLE
That's cool but can't that just be an alias?

### ISSUE THREAD

**Issue by SimonGodefroid** [natethinks/jog#5]
I struggled knowing where to put the script at step 2. ("place it somewhere in your $PATH."), so I ended up doing
```bash
alias plop='less ~/.zsh_history_ext | grep -a --color=never "${PWD}   " | cut -f1 -d"|" | tail'
```
in my .zshrc, it kind of does the job.

**Comment by natethinks** [comment]
That will definitely do the job, you can also add it as another .zshrc function instead of an alias, same difference.

This is completely up to personal preference, but in my opinion everyone should have a ~/bin directory included in your path for scripts you wrote yourself, or things like this you copied from github.

**Comment by fritx** [comment]
Two kind of ways is fine to me.

btw, @SimonGodefroid `cut -f1 -d"|"` should be `cut -f1 -d"⋮"` instead
